-- Hyprland config, Lua format (Hyprland >= 0.55).
-- hyprlang (`hyprland.conf`) is deprecated and will be removed; this file takes
-- precedence over hyprland.conf whenever it exists.
--
-- API reference: /usr/share/hypr/stubs/hl.meta.lua
-- Wiki:          https://wiki.hypr.land/Configuring/Start/

local home = os.getenv("HOME")


------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
-- Fallback for any monitor without an explicit rule. Declared first so the
-- per-monitor rules below override it.
hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = "auto",
})

-- monitors.conf is generated by hyprdynamicmonitors (systemd user unit), which
-- still emits hyprlang `monitor=` lines and whose TUI edits them in place. Lua
-- configs cannot `source` hyprlang, so translate those lines here instead of
-- forking the generator.
local function load_hyprlang_monitors(path)
    local file = io.open(path, "r")
    if not file then
        return
    end

    for line in file:lines() do
        local body = line:match("^%s*monitor%s*=%s*(.+)$")
        if body then
            local fields = {}
            for field in (body .. ","):gmatch("([^,]*),") do
                fields[#fields + 1] = (field:gsub("^%s+", ""):gsub("%s+$", ""))
            end

            local spec = { output = fields[1] or "" }
            local i

            if fields[2] == "disable" or fields[2] == "disabled" then
                spec.disabled = true
                i = 3
            else
                spec.mode     = fields[2] or "preferred"
                spec.position = fields[3] or "auto"
                spec.scale    = fields[4] or "auto"
                i = 5
            end

            -- Trailing fields are flat key,value pairs: transform,0,vrr,0,...
            while fields[i] do
                local key, value = fields[i], fields[i + 1]
                if key == "disable" then
                    spec.disabled = true
                    i = i + 1
                elseif key == "" then
                    i = i + 1
                elseif key == "transform" or key == "vrr" or key == "bitdepth" then
                    spec[key] = tonumber(value)
                    i = i + 2
                else
                    spec[key] = value
                    i = i + 2
                end
            end

            hl.monitor(spec)
        end
    end

    file:close()
end

load_hyprlang_monitors(home .. "/.config/hypr/monitors.conf")


---------------------
---- MY PROGRAMS ----
---------------------

local terminal    = "kitty"
local fileManager = "dolphin"
local menu        = home .. "/.config/hypr/scripts/Wofi.sh"


-------------------
---- AUTOSTART ----
-------------------

-- Services are managed by systemd user units via uwsm.
-- Enable with: systemctl --user enable swaync hyprpolkitagent waybar hypridle
--              hyprsunset hyprdynamicmonitors cliphist-text cliphist-image


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- Session-wide env vars live in ~/.config/environment.d/10-hyprland.conf


-----------------------
---- PERMISSIONS ----
-----------------------

-- Permission changes require a Hyprland restart and are not applied
-- on-the-fly, for security reasons.

-- hl.config({ ecosystem = { enforce_permissions = true } })

-- hl.permission({ binary = "/usr/(bin|local/bin)/grim", type = "screencopy", mode = "allow" })
-- hl.permission({ binary = "/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", type = "screencopy", mode = "allow" })
-- hl.permission({ binary = "/usr/(bin|local/bin)/hyprpm", type = "plugin", mode = "allow" })


-----------------------
---- LOOK AND FEEL ----
-----------------------

-- SwayNC layer rules. 'swaync-control-center' is the history/control panel,
-- 'swaync-notification-window' is the pop-up notifications.
-- NOTE: layer rules match on `namespace`; the old .conf used `match:class`,
-- which is not a valid layer-rule prop.
hl.layer_rule({
    name         = "swaync-control-center",
    match        = { namespace = "swaync-control-center" },
    blur         = true,
    ignore_alpha = 1,
})

hl.layer_rule({
    name         = "swaync-notification-window",
    match        = { namespace = "swaync-notification-window" },
    blur         = true,
    ignore_alpha = 1,
})

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
    general = {
        gaps_in  = 5,
        gaps_out = 20,

        border_size = 2,

        col = {
            active_border   = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
            inactive_border = "rgba(595959aa)",
        },

        -- Set to true to enable resizing windows by dragging borders and gaps
        resize_on_border = false,

        -- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Tearing/
        allow_tearing = false,

        layout = "dwindle",
    },

    decoration = {
        rounding       = 10,
        rounding_power = 2,

        active_opacity   = 1.0,
        inactive_opacity = 1.0,

        shadow = {
            enabled      = true,
            range        = 4,
            render_power = 3,
            color        = "rgba(1a1a1aee)",
        },

        blur = {
            enabled  = true,
            size     = 3,
            passes   = 1,
            vibrancy = 0.1696,
        },
    },

    animations = {
        enabled = true,
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/
    dwindle = {
        preserve_split = true,
    },

    -- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/
    master = {
        new_status = "master",
    },

    misc = {
        force_default_wallpaper = 0,     -- 0 or 1 disables the anime mascot wallpapers
        disable_hyprland_logo   = false, -- true disables the random hyprland logo background
    },
})

-- Default curves, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint",   { type = "bezier", points = { { 0.23, 1 },    { 0.32, 1 }  } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 }  } })
hl.curve("linear",         { type = "bezier", points = { { 0, 0 },       { 1, 1 }     } })
hl.curve("almostLinear",   { type = "bezier", points = { { 0.5, 0.5 },   { 0.75, 1 }  } })
hl.curve("quick",          { type = "bezier", points = { { 0.15, 0 },    { 0.1, 1 }   } })

hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })

-- "Smart gaps" / "No gaps when only", see
-- https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- Uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })


---------------
---- INPUT ----
---------------

hl.config({
    input = {
        kb_layout  = "us",
        kb_variant = "",
        kb_model   = "",
        kb_options = "",
        kb_rules   = "",

        follow_mouse = 1,

        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

        touchpad = {
            natural_scroll = true,
        },
    },
})

hl.device({
    name        = "pixa3854:00-093a:0274-touchpad",
    sensitivity = 0,
})

hl.device({
    name          = "logitech-pro-2-mouse-1",
    sensitivity   = 0.1,
    accel_profile = "flat",
})

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Gestures/
hl.gesture({
    fingers   = 3,
    direction = "horizontal",
    action    = "workspace",
})


---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

local workspaceTerminal = "name:Terminal"
local workspaceNotes    = "name:Notes"
local workspaceChat      = "name:Chat"

-- See https://wiki.hypr.land/Configuring/Basics/Binds/
hl.bind(mainMod .. " + Return",    hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + E",         hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V",         hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + P",         hl.dsp.window.pseudo())          -- dwindle
hl.bind(mainMod .. " + O",         hl.dsp.window.pin())
hl.bind(mainMod .. " + comma",     hl.dsp.layout("togglesplit"))    -- dwindle
hl.bind(mainMod .. " + D",         hl.dsp.exec_cmd(menu))

-- Toggle tabbed (grouped) windows
hl.bind(mainMod .. " + slash", hl.dsp.group.toggle())

-- Switch windows in a tab group
hl.bind(mainMod .. " + CONTROL + h", hl.dsp.group.prev())
hl.bind(mainMod .. " + CONTROL + l", hl.dsp.group.next())

-- Move focus with mainMod + hjkl
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "l" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "r" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "d" }))

-- Switch workspaces with mainMod + [0-9], move the active window with + SHIFT
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Named workspaces
hl.bind(mainMod .. " + T", hl.dsp.focus({ workspace = workspaceTerminal }))
hl.bind(mainMod .. " + N", hl.dsp.focus({ workspace = workspaceNotes }))
hl.bind(mainMod .. " + C", hl.dsp.focus({ workspace = workspaceChat }))

hl.bind(mainMod .. " + SHIFT + T", hl.dsp.window.move({ workspace = workspaceTerminal }))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.window.move({ workspace = workspaceNotes }))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.window.move({ workspace = workspaceChat }))

-- Special workspaces (scratchpads)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

hl.bind(mainMod .. " + M",         hl.dsp.workspace.toggle_special("music"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.window.move({ workspace = "special:music" }))

hl.bind(mainMod .. " + I",         hl.dsp.workspace.toggle_special("private"))
hl.bind(mainMod .. " + SHIFT + I", hl.dsp.window.move({ workspace = "special:private" }))

-- Pick from active special workspaces
hl.bind(mainMod .. " + grave", hl.dsp.exec_cmd(home .. "/.config/hypr/scripts/SpecialWorkspaces.sh"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume",  hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume",  hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",         hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",      hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Monitor controls
hl.bind(mainMod .. " + CTRL + 1", hl.dsp.workspace.move({ monitor = "eDP-1" }))
hl.bind(mainMod .. " + CTRL + 2", hl.dsp.workspace.move({ monitor = "DP-3" }))
hl.bind(mainMod .. " + CTRL + 3", hl.dsp.workspace.move({ monitor = "DP-2" }))

-- SwayNC notification center
hl.bind(mainMod .. " + CTRL + N", hl.dsp.exec_cmd("swaync-client -t"))

-- Reload Waybar
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("systemctl --user restart waybar"))

-- Lock screen
hl.bind(mainMod .. " + SHIFT + L", hl.dsp.exec_cmd("hyprlock"))

-- Screenshot controls
hl.bind(mainMod .. " + PRINT",         hl.dsp.exec_cmd("hyprshot -m window"))
hl.bind("PRINT",                       hl.dsp.exec_cmd("hyprshot -m output"))
hl.bind(mainMod .. " + SHIFT + PRINT", hl.dsp.exec_cmd("hyprshot -m region"))

-- Clipboard history (cliphist) — pick a past entry and copy it back, then Ctrl+V
hl.bind(mainMod .. " + SHIFT + V",
    hl.dsp.exec_cmd([[cliphist list | wofi --dmenu --insensitive -p "Clipboard" | cliphist decode | wl-copy]]))

-- hyprwhspr — toggle speech-to-text (press once to start, again to stop)
hl.bind("SUPER + SHIFT + D",
    hl.dsp.exec_cmd("/usr/lib/hyprwhspr/config/hyprland/hyprwhspr-tray.sh record"),
    { description = "Speech-to-text" })


--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/

-- Ignore maximize requests from apps. You'll probably like this.
hl.window_rule({
    name  = "suppress-maximize-events",
    match = { class = ".*" },

    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})
