context.modules = [
  {
    name = libpipewire-module-echo-cancel
    args = {
      library.name   = aec/libspa-aec-webrtc
      node.name      = "Echo Cancel Sink"
      aec.args = {
        webrtc.extended_filter  = true
        webrtc.delay_agnostic   = true
        webrtc.high_pass_filter = true
        webrtc.noise_suppression = true
        webrtc.gain_control     = true
      }
      capture.props = {
        node.name = "Echo Cancel Capture"
      }
      source.props = {
        node.name        = "Echo Cancel Source"
        node.description = "Echo Cancel Source"
      }
      sink.props = {
        node.name        = "Echo Cancel Sink"
        node.description = "Echo Cancel Sink"
      }
      playback.props = {
        node.name = "Echo Cancel Playback"
      }
    }
  }
]
