context.modules = [
  {
    name = libpipewire-module-filter-chain
    args = {
      node.name        = "Noise Gate Source"
      node.description = "Noise Gate Source"
      media.name       = "Noise Gate Source"
      filter.graph = {
        nodes = [
          {
            type   = lv2
            name   = gate
            plugin = "http://calf.sourceforge.net/plugins/Gate"
            control = {
              threshold   = 0.015
              attack      = 2.0
              release     = 150.0
              range       = 0.00002
              ratio       = 20.0
              makeup      = 1.0
              knee        = 1.0
              detection   = 0.0
              stereo_link = 1.0
            }
          }
        ]
        inputs  = [ "gate:in_l" "gate:in_r" ]
        outputs = [ "gate:out_l" "gate:out_r" ]
      }
      capture.props = {
        node.name       = "Noise Gate Capture"
        node.passive    = true
        audio.rate      = 48000
        audio.channels  = 2
        audio.position  = [ FL FR ]
      }
      playback.props = {
        node.name       = "Noise Gate Playback"
        media.class     = Audio/Source
        audio.rate      = 48000
        audio.channels  = 2
        audio.position  = [ FL FR ]
      }
    }
  }
]
