monitor.alsa.rules = [
  {
    matches = [
      { device.name = "~alsa_card.usb-C-Media_Electronics_Inc.*" }
    ]
    actions = {
      update-props = {
        device.disabled = true
      }
    }
  }
]
