[font]
normal = { family = "MesloLGM Nerd Font", style = "Regular" }

[window]
# opacity = 0.6
# blur = true

[colors.primary]
background = "#000000" # default is #181818

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "ToggleViMode"

